/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.0 Update 1
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2016 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "I2C.h"
#include "I2C_I2C.h"
#include "I2C_PINS.h"
#include "I2C_I2C_PVT.h"
#include "I2C_PVT.h"
#include "I2C_BOOT.h"
#include "serial.h"
#include "serial_SPI_UART.h"
#include "serial_PINS.h"
#include "serial_SPI_UART_PVT.h"
#include "serial_PVT.h"
#include "serial_BOOT.h"
#include "butt_pin.h"
#include "butt_pin_aliases.h"
#include "read_battery.h"
#include "BOARD_LED.h"
#include "BOARD_LED_aliases.h"
#include "RED_LED.h"
#include "RED_LED_aliases.h"
#include "YELLOW_LED.h"
#include "YELLOW_LED_aliases.h"
#include "GREEN_LED.h"
#include "GREEN_LED_aliases.h"
#include "I2C_SCBCLK.h"
#include "I2C_sda.h"
#include "I2C_sda_aliases.h"
#include "I2C_scl.h"
#include "I2C_scl_aliases.h"
#include "I2C_SCB_IRQ.h"
#include "serial_SCBCLK.h"
#include "serial_tx.h"
#include "serial_tx_aliases.h"
#include "serial_SCB_IRQ.h"
#include "serial_rx.h"
#include "serial_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "CyLFClk.h"

/*[]*/

